### ISSUE TITLE
Save profile operation: Cannot modify header information - headers already 

### ISSUE THREAD

**Issue by bekopharm** [impresspages-plugins/User#1]
"Save" in /profile is not working when Notices are enabled due to the following notice:

```
Notice: Array to string conversion in Plugin/User/Model.php:85
```

**Comment by maskas** [comment]
Have you done any modifications?

**Comment by bekopharm** [comment]
Absolutly not, no.

Edith says: I take it that you didn't expect this to happen. I'll dump the Array tomorrow and see what data Model.php really gets.

**Comment by bekopharm** [comment]
This is the data that gets to Model.php:85

```
array(5) {
  ["securityToken"]=>
  string(32) "9ed50d37e37e81ffa8923ba6fe4f5a2c"
  ["antispam"]=>
  array(2) {
    [0]=>
    string(0) ""
    [1]=>
    string(32) "57518b3720b46c8bd56a88379f05d7fb"
  }
  ["sa"]=>
  string(11) "User.update"
  ["id"]=>
  string(1) "2"
  ["email"]=>
  string(20) "mail@example.com"
}
```

Edith: replaced mail address with example one, of course.

Model.php:85:

```
$data = array_intersect($data, array('username', 'email'));
```

After that the notice is spawned and $data looks like that:

```
array(0) {
}
```

Also no data is written to db (obviously).

**Comment by maskas** [comment]
Thanks for debug info. Looking at it.

**Comment by maskas** [comment]
I also get an empty array at that point. But can't reproduce the same warning notice. I believe it might be issue of PHP versions. Does this commit help? https://github.com/impresspages-plugins/User/commit/3c1d3e32e57110529bba73f1f8310e6889fb35f3

**Comment by bekopharm** [comment]
3c1d3e32e57110529bba73f1f8310e6889fb35f3 fixes this for me.

php is 5.4.4-14+deb7u8

**Comment by bekopharm** [comment]
So.. I guess I have to close this myself? Didn't know... ;)

**Comment by maskas** [comment]
+1
